### ISSUE TITLE
Changing the package name from me/cakenggt/Ollivanders to your server's

### ISSUE THREAD

**Issue by iarepandemonium** [Azami7/Ollivanders2#1]
Clearly you don't care, but this is kind of offensive to me personally.  Not sure if cakenggt agrees or not, but I have contacted him because it actually upsets me.  This was his work and it's like ripping an author's watermark off a picture doing that.  I never disliked Pottercraft before, but this is kind of scummy.

**Comment by Azami7** [comment]
It is a namespace not a watermark of ownership. This is exactly how Java intended this to behave. We didn't want to clobber the original package namespace, which we also have in our development environments.  Attribution is done in comments with JavaDoc with things like the @author tag and that has not been changed.  No one is trying to claim authorship.

Also, I do find amusing that you are offended by us changing the namespace of a package but you have no problems with violating the cr@p out of JK Rowlings copywrite.

**Comment by iarepandemonium** [comment]
Changing someone's code work esp someone who was the entire reason why I code is a little bit more personal.
