### ISSUE TITLE
[Ollivanders2 2.2.6] Mastered spells are spammable without a wand.

### ISSUE THREAD

**Issue by Zundrel** [Azami7/Ollivanders2#110]
Spam clicking allows the player to shoot their master spell repeatedly without a wand without it being reset to nothing. This is due to the fact you do not set the players master spell to null even if they don't have their destined wand equipped. 

This is easily fixable by checking if their wandCheck != 1 and doing the necessary things to set their master spell to null inside of PlayerInteractEvent.

This is a VERY important and vital fix. I've performed this fix on my fork in this commit https://github.com/Zundrel/Ollivanders-Reborn/commit/0038be7c79a460e170b418b1e9aae5ba467a1751.

This issue is part of your non-verbal spell rewrite in https://github.com/Azami7/Ollivanders2/commit/d8b5a8a30f79e96f84fc26d1f8497ed4a77b7b6a.

P.S. - I recommend changing how non-verbal spells work to how I did it. It's much more user-friendly.

**Comment by Azami7** [comment]
I have added your fix to 2.2.6. Your commit for where you rewrite non-verbal spells is full of non-relevant stuff (looks like you changed {} style and it shows all that in your commit as changes) and there was too much noise to figure out what was relevant. If you want to send me a clean diff from the final 2.2.6 GA then I'll take a look.

**Comment by Azami7** [comment]
2.2.6 release is on Spigot now - https://www.spigotmc.org/resources/ollivanders2.38992/update?update=211166

**Comment by Zundrel** [comment]
All I changed for the non verbal spells was allow you to shift forward with right-click and shift back with shift right-click. If the player has no mastered spells in that case it would do the destined wand affect.

**Comment by Slord6** [comment]
That would be a nice feature, I've always found having to cycle all the way through again frustrating.

**Comment by autumnwoz** [comment]
I haven't done any testing with mastered spells so I can't confirm that these features work, but as per [the original plugin](https://dev.bukkit.org/projects/ollivanders/pages/spells) you sneak and right click to go backwards so that doesn't need to be added.  It also states that the mastered spell is intentionally not set to null for easy repeated casting.  We just added a basic spell cool-down so I think we can remove this fix.

**Comment by autumnwoz** [comment]
Looks like scrolling only works in one direction, but the spamming is fixed.  I'm closing this issue and opening a new one #122 for scrolling.
