### ISSUE TITLE
Animagus Potion

### ISSUE THREAD

**Issue by EmperorRiley** [Azami7/Ollivanders2#112]
Hello!
I wasn't sure if the animagus potion was supposed to be unbrewable or if it's a bug?
The code say's nether wart**s**

And I'm not sure if I'm just not reading it correctly when I think it means the nether wart item?

Any help is appreciated. 

Thank you

**Comment by Azami7** [comment]
Ah, I see why. There was a material "NETHER_WARTS" but that has been changed to "NETHER_WART" and the original is now "LEGACY_NETHER_WARTS". I'll get that fixed and an update built.
