### ISSUE TITLE
Protego - what does it do and is it working?

### ISSUE THREAD

**Issue by Azami7** [Azami7/Ollivanders2#142]
Protego just seems to kill itself as soon as it gets started. What is this spell supposed to be doing? There are no comments so not sure...

**Comment by Zundrel** [comment]
You have to sneak to use it: https://github.com/Azami7/Ollivanders2/blob/8712c74717958015222b98c7494b51b4d7d5b2dc/Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/PROTEGO.java#L45

**Comment by Azami7** [comment]
Yea I did that and it still stopped as soon as it started. I am not sure what the original plugin authors intended for this spell but it doesn't seem to align with the actual spell behavior in HP.

**Comment by Azami7** [comment]
Figured out why it stops right away - this spell needs a refactor though.
