### ISSUE TITLE
Task # 2 Server Warning

### ISSUE THREAD

**Issue by larson-link** [Azami7/Ollivanders2#179]
I am running a fresh install of the spigot mc server that runs fine. When I add Ollivanders2 I get an excetion: 

> [23:51:12] [Server thread/WARN]: [Ollivanders2] Task #2 for Ollivanders2 v2.2.7 generated an exception
> java.lang.NoClassDefFoundError: me/libraryaddict/disguise/disguisetypes/TargetedDisguise
> 	at net.pottercraft.Ollivanders2.Player.O2Players.addPlayer(O2Players.java:71) ~[?:?]
> 	at net.pottercraft.Ollivanders2.Ollivanders2.getO2Player(Ollivanders2.java:1308) ~[?:?]
> 	at net.pottercraft.Ollivanders2.OllivandersSchedule.oeffectSched(OllivandersSchedule.java:121) ~[?:?]
> 	at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:59) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
> Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.disguisetypes.TargetedDisguise
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
> 	... 11 more

**Comment by larson-link** [comment]
[latest.log](https://github.com/Azami7/Ollivanders2/files/2321132/latest.log)

**Comment by Azami7** [comment]
Looks like we missed guarding someplace that requires libsDisguises. Thanks for sending the stack trace.

**Comment by Azami7** [comment]
Pull request to fix this - https://github.com/Azami7/Ollivanders2/pull/182

However, without LibsDisguises many of the spells in the game will be disabled, including most transfiguration spells so you may want to consider adding that (which will also fix this issue for your server).

**Comment by larson-link** [comment]
I installed a free version of libdisguises however I am still getting the error. I think I may have downloaded it incorrectly somehow. any suggestions for where to download it?

**Comment by crazyshotgug69** [comment]
Since it is a paid plugin, you are not meant to get it free.

**Comment by Azami7** [comment]
Yea, sadly it is the only one we've found out there that does this and turning players in to other entities requires some non-trivial hacking of the MC packets that we didn't want to re-engineer and maintain.
