### ISSUE TITLE
Apparate coords and animagus issues

### ISSUE THREAD

**Issue by Honeki** [Azami7/Ollivanders2#264]
Using the admin commands, I cannot get the animagus potion. I also cannot craft the animagus potion no matter what I do. The ingredients are added when making potions but not consumed, I should also add. They just float in the middle of the cauldron and can be picked up again. Another thing is that I cannot apparate with coords. I tried "apparate x y z", "apparate x,y,z", "apparatex y z" and almost all other forms ,-,

**Comment by Honeki** [comment]
the file says 2.2.8 and so does the ingame command . Also, apparate is not in a book ,-,

**Comment by Honeki** [comment]
> What version are you running?

along with the message above, i found a few other errors the past two days. I went back to an earlier version, and the potions command gave me the animagus potion. I was also able to apparate with coords then. For some reason, in the older version I tested (just one down from the 2.8.8 beta), I was able to change other people's animagus form using the 0Players.txt thing but not my own. It just kept reverting me back to a horse, which also wasn't my original form. I was a cave spider, but after the restart i was stuck as a horse, irreversibly. It may have been that I changed the other players' forms before restarting the server, so they wouldn't have had a chance to change into something else. Anyway, a bigger problem now is that I cannot cycle through my mastered spells with the new version (2.8.8 beta, the latest file on spigot). Again, apparating with coords was possible in the previous version, animagus potion doesn't appear in the new version (but it still works if you pull the potion from a previous plugin version), apparate isn't in any of the books in either version. Additionally, the versoin below 2.8.8 there is a collision glitch for whenever you cast melofors or something like that, you'd just hit yourself unless you were backing up really fast.

really the only problem i have right now is apparating with coords and cycling through spells in 2.8.8. The rest of what I said is just bugs I noticed

**Comment by Honeki** [comment]
:I and the scoreboard wont go away even after turning off houses in the config and getting rid of the plugin. (I was just reseating the plugin, not permanently. Still a really good job, and thanks for it)

**Comment by Azami7** [comment]
Apparate not being in a book is already filed - https://github.com/Azami7/Ollivanders2/issues/238

Potion brew success is learned if you have book learning enabled (see the release notes - https://www.spigotmc.org/resources/ollivanders2.38992/update?update=247093). You will get a random unsuccessful potion until you learn it well enough and Animagus potion is one of the most advanced so it requires more time to learn.

The give command is indeed giving the antidote potion. I'll take a look at that.

**Comment by Azami7** [comment]
Fixed the animagus potion and also spell rotation (which is supposed to be done with the wand in your off hand but was having a sad too). It will not work if you dual-wield wands, however, because the Minecraft game will always give precedence to the primary hand (https://minecraft.gamepedia.com/Dual_wield) so that action will always override any off-hand action.

**Comment by Azami7** [comment]
Sorry, should have clarified that "fixed" is I have fixes for them in review.

**Comment by Azami7** [comment]
For apparate coordinates, I think I remember fixing an issue that would have affected any spell that takes arguments but I am not sure which change that was now. It definitely works on 2.2.9 so I'll work on getting that out soon since it is probably faster than trying to find what change fixed that.

**Comment by Azami7** [comment]
Fixed released - https://www.spigotmc.org/resources/ollivanders2.38992
