### ISSUE TITLE
Ollivanders fails to load: Invalid plugin.yml

### ISSUE THREAD

**Issue by Slord6** [Azami7/Ollivanders2#3]
If I download version 2.0 from the [spigot site](https://www.spigotmc.org/resources/ollivanders2.38992/history) and allow the autoupdate to run, Ollivanders fails to start on the next server startup. I think this is because the plugin goes and downloads an outdated version (v0.16)

```
[21:02:44 INFO]: [Ollivanders2] About to download a new update: Ollivanders v0.16
[21:02:44 INFO]: [Ollivanders2] Downloading update: 100% of 181 bytes.
[21:02:44 INFO]: [Ollivanders2] Finished updating.
```

I took a quick look and compared the plugin.yml before and after and couldn't see any difference and so I think the changes made on this fork to update author/version/etc in plugins.yml then don't match up with the rest of the plugin? I'm not sure about this, though, with the 'update' only being 181 bytes.

**Comment by Azami7** [comment]
This is fixed.  The issue was with the auto-updater from the original Ollivanders plugin.  We actually removed this since we're making changes to the plugin that will be incompatible with earlier versions of MC so it should not try to update itself.
