### ISSUE TITLE
Support to 1.14.4

### ISSUE THREAD

**Issue by Puoko123** [Azami7/Ollivanders2#300]
For the love of God, add support for 1.14.4 because most spells don't work. Like apparate and glacius, aguamenti, duro, fatuus aurum...

And update the plug-in please, add new spells. I LOVE the plug-in.

**Comment by Azami7** [comment]
:) Been working on it but life got a bit busy for all of us working on this and we need to finish it up. The changes for 1.14 were pretty significant. 

I'll update this when we have a beta version ready for you to try.

**Comment by Azami7** [comment]
This has been added. https://www.spigotmc.org/resources/ollivanders2.38992/update?update=361770
