### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by threlief** [Azami7/Ollivanders2#309]
hello i just currently put this on a 1.13.2 server im starting and when i try to sort in a house it comes up with a internal error and i followed the config examples you have and changed nothing so idk whats wrong please help :) also spells dont work wither :/

**Comment by Azami7** [comment]
can you send what it is in your log file at start up? without more information, I can't really debug what may be happening.

**Comment by Azami7** [comment]
resolving this since there was no reply from the submitter for several months.
