### ISSUE TITLE
How do I make this thing work

### ISSUE THREAD

**Issue by Koszatniczek** [Azami7/Ollivanders2#352]
Ok, so I have spent the last 4 hours starting and restarting my server, getting tons of error messages, changing spigot versions, java versions, and ollivander versions. The best I could get to, was to make it semi usable [the plugin loads and i can cast SOME spells], but the console is getting spammed with error messages about tasks, and most stuff doesn't work.

Hence my question: Can someone tell me WHICH version of spigot exactly do I need [highest possible preferably], and which version of Ollivanders, and also which java version, to have it work and be stable.

I even fecking had a version of olli for 1.14, my server was 1.14 / 1.15 and the console errors told me that olli requires 1.13, what the hell.

Has anyone managed to get it to work stable? I really loved this plugin back then and want to base my server on it, but just can't get it to work, no matter which versions of spigot / java / plugin i use.

**Comment by Azami7** [comment]
Which version of Ollivanders are you trying to use? Actual log output would be helpful. 

And yes, lots of people run this - including us on several servers. I am actually not aware of anyone having issues with it loading except if their MC is too old and that doesn't cause exceptions, the plugin just exits with a version message.

**Comment by Koszatniczek** [comment]
Depends, I used lots of different spigot versions, java versions and plugin versions. I can't get it to work anywhere. Sometimes it works, but some spells and features do not and my console gets spammed with errors.

Last error spam I had was:
08.11 20:40:35 [Server] Server thread/WARN Task #10 for Ollivanders2 v2.4.1 generated an exception
08.11 20:40:35 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: null

Can you suggest me which Server version, Java version and Plugin version should I use to make it work? [all of the above, I can change any of those to whatever is needed]

I will run it on the suggested versions and if anything comes up I'll post logs

**Comment by Azami7** [comment]
MC 1.14 or later - Ollivanders2-2.4.*
MC 1.13 or later - Ollivanders2-2.3.*
MC 1.12 or later - Ollivanders2-2.2.*
MC 1.9-1.11.2 - Ollivanders2-2.1.*

(this is also on our spigot page)

Generally speaking, using a higher version of MC than what is listed for a version should work because MC does a decent job of maintaining backwards compatibility but the reverse is not true. For example, you cannot use Ollivanders2-2.4 on MC lower than 1.14 because it relies on code in Spigot API in 1.14 and higher. I also recommend running the most current of any version since it will have bug fixes for issues discovered. If you are running MC 1.14 or higher, that would be 2.4.1-alpha, for MC 1.13 that would be 2.3.2-alpha.

I cannot tell what is going on from those 2 lines of log code, I'd need to either see the rest of the logs or know what was happening on the server when it was written. Usually an exception like that would write a stack trace in the logs - this would be the most useful. If you do not see that, you can try running debug mode which will give a lot more output. You can enable it either via the config file (and restart) or by typing /olli debug on your running server.

**Comment by Koszatniczek** [comment]
Ok, I have ran a fresh server, with only Ollivanders. 
Spigot for minecraft version 1.15.2
Java: 11
Ollivanders2 version: 2.4.1

The errors start appearing and spamming the console after I use the command to give myself all books. 
After the errors started spamming the console I have tested 3 spells:
- Lumos, works
- Vingardium leviosa, doesn't do anything
- Spongify, doesn't do anything

I suspect most other spells will not work either, same as the last time I have tried

Error log:
https://pastebin.pl/view/22334ef2

**Comment by Koszatniczek** [comment]
I have now tried to run it on minecraft 1.14.4 [with a clean world too] and this is what I get:
https://pastebin.pl/view/a25d9019

Again, some parts work, some don't:
- invisiblity cloak works
- wands give off particles [when it's a wand for me, right click]
- lumos works
- avada kedavra doesn't work [doesn't do anything]
- spongify doesn't work
- fiendfyre doesn't work
- other spells do not work

This, plus I get the error spam right after loggin in [without even using any commands this time]

**Comment by Koszatniczek** [comment]
Oh, also when I try to run with the version of java other plugins work on [not 11, I think it's 8 or so] then I get this error and olli doesn't even load:

10.11 10:33:41 [Server] ERROR Could not load 'plugins/Ollivanders2-2.4.1.jar' in folder 'plugins'
10.11 10:33:41 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/pottercraft/ollivanders2/Ollivanders2 has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime

**Comment by Koszatniczek** [comment]
I have also tried java11 version of another server - paper [built on spigot I guess] that was recommended, it is also generating errors, and the spells do not work, the same as with the above

Logs from Paper 1.15.2:
https://pastebin.pl/view/8b787559

**Comment by Koszatniczek** [comment]
This plugin is kind of the main reason I got a server hosted [I played olli1 but then it died], and I really want to get it to work, but no matter what I do I can't for the life of me do that :/ I am testing everything, even contacted my hosting provider, nothing helps damnit.

**Comment by Azami7** [comment]
java.lang.UnsupportedClassVersionError is a java error - not a minecraft error. The only thing I can find when searching for that is running something compiled on a newer version of java with an old version of java.

I am not sure what OS you use but I would start by trying to see if you can get it to run on your own computer. If you are using Mac or Linux, this should be pretty easy. I am not familiar with Windows so I am not sore what you need to do there. Start with a clean build of MC 1.16.5 following Spigots instructions - https://www.spigotmc.org/wiki/buildtools/ - and then add Ollivanders to the plugins directory. I would also verify which version of java you are running by doing java -version.

**Comment by Azami7** [comment]
Resolving since there has been no response from the submitter since Nov. Please re-open if you continue to have issues.
