### ISSUE TITLE
Plugin does not work / is not displayed at /plugins

### ISSUE THREAD

**Issue by Ankyrex** [Azami7/Ollivanders2#356]
I installed the Olivanders2 plugin for my 1.16.5 server. (Latest version). However, the plugin is not displaying at /pl or /plugins, commands do not work either. Does anyone know why?

**Comment by Azami7** [comment]
I am not clear what you mean by "is not displaying at /pl or /plugins"? Can you add more details to specifically what you are doing that isn't working or send server log output?

**Comment by Ankyrex** [comment]
> I am not clear what you mean by "is not displaying at /pl or /plugins"? Can you add more details to specifically what you are doing that isn't working or send server log output?

I mean if I do /pl or /plugins, all installed plugins are showing up. Ollivanders isnt showing up, but I installed it right

**Comment by Azami7** [comment]
You'll need to look at the log output from your server, that will show why it was not loaded if it has been added to the /plugins directory for your server.

**Comment by Azami7** [comment]
Checking in - were you able to check your server logs to see if there was anything useful?

**Comment by Azami7** [comment]
Resolving this since the requestor has not replied back in 3 weeks.
