### ISSUE TITLE
Worldguard conflicts

### ISSUE THREAD

**Issue by Thenewtaylor** [Azami7/Ollivanders2#357]
Hello! I am having issues on my server where I cannot cast certain spells in my regions. For example, we have our houses protected using worldguard, but I cannot cast Aliquam Floo on my fireplace because of something to do with the worldguard. I just get "A powerful protective magic blocks your spell." The same thing comes up with avada kedavra and other random spells. I am not sure how to go about removing this to fix the problem.

**Comment by Azami7** [comment]
The plugin is designed to honor any worldguard settings if you have them enabled. For example, Alliquam Floo requires the caster have both Interact and Build permissions. Avada Kedavra requires the caster have PVP and Damage Animals. If you have prevented these in the region with WorldGuard flags, they cannot be cast.

**Comment by Thenewtaylor** [comment]
Omg thank you, king <3 Great plugin btw

**Comment by Azami7** [comment]
:) glad it worked!

**Comment by Thenewtaylor** [comment]
Hi, again. <3 so I broke something LOL. Basically we had to tweak some stuff on our server and I temporarily removed the plugin. Apparently, I had 2 Horcruxes in the world. When the plugin was deleted, the Horcruxes were destroyed, but I still only have like 2.5 hearts and I do not know how to reset my health. Is there a way I can restore my health to max?

**Comment by Thenewtaylor** [comment]
LOL I fixed it <3 Thank you anyways.

**Comment by Azami7** [comment]
Oh how did you fix it? Horcruxes were ish kinda working in the original Ollivanders and honestly we have  not really looked at them much because our server doesn't use them. It is on our to-do list to redo the implementation to make it more stable.

**Comment by Thenewtaylor** [comment]
I used /attribute to get my health back. Honestly, it was a simple manual fix that I was too dumb to realize LOL. Do you know if it is possible to change the names of the spellbook or to make our own spellbooks somehow? Our server loves your plugin, but we are trying to make our own lore, swaying away from Harry Potter as much as we can.

**Comment by Azami7** [comment]
You can definitely make your own books though the plugin wont know to recognize them for things like the bookLearning feature. Setting lore on a book I have never done in-game but there is a plugin that is all for making books - [https://www.spigotmc.org/resources/interactivebooks.45604/](https://www.spigotmc.org/resources/interactivebooks.45604). I have not tried it but it looks promising. We add special server-unique stuff for our plugin with a second plugin that works with Ollivanders. 

It is a cool idea to allow for servers to create their own books. I'll add that as a possible new feature to the backlog.

**Comment by Azami7** [comment]
Resolving since it is working for you.
