### ISSUE TITLE
Wiki items command incorrect

### ISSUE THREAD

**Issue by Slord6** [Azami7/Ollivanders2#431]
The wiki page for items could do with updating to the correct commands,

It currently lists ` /ollivanders2 item <item name>` rather than `items`.

Also, it took me some trial and error to work out what to put in as the item name for eg the invisibility cloak; a list of all the possible items would also be handy.

Similarly, it would be great if there was a master list of all the spells with a very brief description of each for reference, but I appreciate that might be a fair chunk of work. I'd be happy to putting in some work to automate that in some way if that would be helpful

**Comment by Azami7** [comment]
Both ````/ollivanders item```` and ````/ollivanders```` items are valid.

You can get a list of all items by running ````/ollivanders item list````

Let me know if this doesn't answer your questions.

**Comment by Slord6** [comment]
Ah, that's great, thanks! Would be good for `/ollivanders2 item list` to be on the items wiki page.

**Comment by Azami7** [comment]
Added
